# Generated by Django 2.1.1 on 2018-09-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetype',
            name='code',
            field=models.CharField(choices=[('STD', 'Standard'), ('MGR', 'Manager'), ('EXEC', 'Executive'), ('CHIEF', 'Chief Executive')], max_length=5),
        ),
    ]
