# Generated by Django 2.1.1 on 2018-10-02 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20181002_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationrequest',
            name='officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.Employee'),
        ),
    ]
