# Generated by Django 2.1.1 on 2018-10-02 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_auto_20181002_0658'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='amendmentrequest',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='applicationrequest',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='assessment',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='idrequest',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='returnsrequest',
            managers=[
            ],
        ),
    ]
